config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }
  devise_scope :user do 
    get 'users/get_phone_number' => "registrations#get_phone_number"
    post "users/verify" => "registrations#verify"
  end
  root 'home#index'
  resources :charges
  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"
  post 'phone_numbers/process_sms' => 'phone_numbers#process_sms'

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  def generate_pin
    self.pin = rand(0000..9999).to_s.rjust(4, "0")
    save
  end

  def twilio_client
    Twilio::REST::Client.new(Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_auth_token)
  end

  def send_pin
    twilio_client.messages.create(
      to: phone_number,
      from: Rails.application.secrets.twilio_phone_number,
      body: "Your PIN is #{pin}",
      media_url: "http://www.toyhalloffame.org/sites/www.toyhalloffame.org/files/toys/square/rubber-duck_0.jpg"
    )
  end

  def verify(entered_pin)
    update(verified: true) if self.pin == entered_pin
  end

  def charge(customer_id, card_id)
    # Amount in cents

    Stripe::Charge.create(
      amount: 1500,
      currency: 'usd',
      customer: customer_id,
      card: card_id
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new session["devise.user_attributes"] do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.image = auth.info.image
    end
  end

  def generate_pin
    self.pin = rand(0000..9999).to_s.rjust(4, "0")
    save
  end

  def twilio_client
    Twilio::REST::Client.new(Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_auth_token)
  end

  def send_pin
    twilio_client.messages.create(
      to: phone_number,
      from: Rails.application.secrets.twilio_phone_number,
      body: "Your PIN is #{pin}",
      media_url: "http://www.toyhalloffame.org/sites/www.toyhalloffame.org/files/toys/square/rubber-duck_0.jpg"
    )
  end

  def verify(entered_pin)
    update(verified: true) if self.pin == entered_pin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  respond_to :html, :js

  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :phone_number, :password, :password_confrimation, :current_password)}
  end

 private
  def after_sign_in_path_for(resource)
    if current_user.phone_number == nil
      users_get_phone_number_path
    else
      edit_user_registration_path(current_user)
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 699

    token = params[:stripeToken]

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      card: token
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Twilio customer',
      currency: 'usd'
    )

    save_stripe_customer_id(user, customer.id)

    customer_id = get_stripe_customer_id(user)

    Stripe::Charge.create(
      amount: 1500,
      currency: 'usd',
      customer: customer_id
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook 
    user = User.from_omniauth(request.env["omniauth.auth"])   
    if user.persisted?
      flash.notice = "#{user.email}, you are signed in!"
      sign_in_and_redirect user, notice: "#{user.email}, you are signed in!"
    else
      flash.notice = "We're sorry, there was an error signing you in."
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def new
    @phone_number = PhoneNumber.new
  end

  def create
    @phone_number = PhoneNumber.create(phone_number: params[:phone_number][:phone_number])
    @phone_number.generate_pin
    @phone_number.send_pin
    respond_to do |format|
      format.js
    end
  end

  def verify
    @phone_number = PhoneNumber.find_by(phone_number: params[:hidden_phone_number])
    @phone_number.verify(params[:pin])
    respond_to do |format|
      format.js
    end
  end

  def render_twiml(response)
    render text: response.text, :content_type => "text/xml"
  end

  def process_sms
    @body = params[:Body]

    twiml = Twilio::TwiML::Response.new do |r|
      if @body == "Yes"
        charge = Stripe::Charge.create(
          customer: "cus_7vySlDB3BvnO6C",
          amount: 1999,
          description: 'Text bro customer',
          currency: 'usd',
          card: "card_17g6VqGqUdrxDDBSJ9do2gk3"
        )
        r.Message "Your order has been received :)"
      else
        r.Message "Maybe next time. Have a great day"
      end
    end
    render_twiml(twiml)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  skip_before_action :verify_authenticity_token

  respond_to :html, :js

  def update
    # Verify if we need to request current password from user
    successfully_updated = if needs_password?(@user, user_params)
      @user.update_with_password(user_params)
    else
      # Remove the virtual current_password
      # attribute update_without_password
      params[:user].delete(:current_password)
      @user.update_without_password(user_params)
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      @user.generate_pin
      @user.send_pin
      respond_to do |format|
        format.html { redirect_to users_get_phone_number_path }
        format.js
      end
    else
      render "edit"
    end
  end

  def get_phone_number
    @user = current_user
  end

  def verify
    @user = User.find_by(phone_number: params[:hidden_phone_number])
    @user.verify(params[:pin])
    respond_to do |format|
      format.js
    end
  end

  def render_twiml(response)
    render text: response.text, :content_type => "text/xml"
  end

  def process_sms
    @body = params[:Body]

    twiml = Twilio::TwiML::Response.new do |r|
      if @body == "Yes"
        charge = Stripe::Charge.create(
          customer: "cus_7vySlDB3BvnO6C",
          amount: 1999,
          description: 'Text bro customer',
          currency: 'usd',
          card: "card_17g6VqGqUdrxDDBSJ9do2gk3"
        )
        r.Message "Your order has been received :)"
      else
        r.Message "Maybe next time. Have a great day"
      end
    end
    render_twiml(twiml)
  end

  private

  def needs_password?(user, user_params)
    # Verify if email changed
    user.email != params[:user][:email] ||
        # Verify if the password has been informed
        params[:user][:password].present?
  end

  def user_params
    params.require(:user).permit(:email, :password, :phone_number, :first_name, :last_name, :image)
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:stripe_publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<h1>Home Page</h1>

<% if user_signed_in? %>
  <p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
<% else %>
  <p><%= link_to "Sign Up", new_user_registration_path %></p>
  <p><%= link_to "Log In", new_user_session_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmsVerification</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/', 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css", media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <div>
      <%= value %>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/phone_numbers/create.js.erb
$('#hidden_phone_number').val('<%= @phone_number.phone_number %>' )
$('#send-pin').hide()
$('#verify-pin').fadeToggle()
$('#pin').focus()

app/views/phone_numbers/new.html.erb
<div id="send-pin">
  <h3>What's your phone number bro?</h3>
  <%= form_for @phone_number, remote: true do |f| %>
    <div class="form-group">
      <%= f.text_field :phone_number %>
    </div>
    <%= f.submit "Send PIN", class: "btn btn-primary", id: 'send-pin-link' %>
  <% end %>
</div>

<div id="verify-pin">
<h3>Enter your PIN</h3>
<%= form_tag phone_numbers_verify_path, remote: true do |f| %>
  <%= hidden_field_tag 'hidden_phone_number', '' %>
  <div class="form-group">
    <%= text_field_tag :pin %>
  </div>
  <%= submit_tag "Verify PIN", class: "btn btn-primary" %>
  <% end %>
</div>
 
<div id="status-box" class="alert alert-success">
  <p id="status-message">Status: Haven’t done anything yet</p>
</div>

app/views/phone_numbers/verify.js.erb
<% if @phone_number.verified %>
  $('#verify-pin').hide()
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-success')
  $('#status-message').text('Success!!')
<% else %>
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-warning')
  $('#status-message').text("Sorry, that wasn't the right pin.")
<% end %>
$('#status-box').fadeToggle()

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>